apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: micro-pay-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: 'nginx'
  rules:
    - host: ${MICRO_PAY_HOSTNAME}
      http:
        paths:
          - backend:
              service:
                name: micro-pay
                port:
                  number: ${MICRO_PAY_PORT}
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ${MICRO_PAY_HOSTNAME}
      secretName: web5
